name: sample-deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Check out Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run the Cake script
        uses: cake-build/cake-action@v3
        with:
          script-path: build.cake
      - name: Publish generated Blazor webassembly to Netlify
        uses: nwtgck/actions-netlify@v2.0
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_API_KEY }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        with:
          publish-dir: .publish/wwwroot
          production-branch: main
          
